const express = require('express')
const router=express.Router()
const {AuthMiddleware}=require("../middleware/AuthMiddleware")
const {EditUser,ForgetPassword,AddToWishList,RemoveFromWishList,GetAllWishListProducts}=require("../controllers/UserController")
router.put("/EditUser",AuthMiddleware,EditUser)
router.put("/ForgetPassword",AuthMiddleware,ForgetPassword)
router.put("/AddToWishList",AuthMiddleware,AddToWishList)
router.delete("/RemoveFromWishList/:id",AuthMiddleware,RemoveFromWishList)
router.get("/GetAllWishListProducts",AuthMiddleware,GetAllWishListProducts)
module.exports = router